# file: game/constants.py

"""
Храним все игровые константы в одном месте для удобства настройки
и "лучших практик" по управлению балансом.
"""

ALTAR_ACTIVATION_MIN_HOURS = 6
ALTAR_ACTIVATION_MAX_HOURS = 8  # Пока не используется напрямую, при желании можно задать рандомные задержки
ALTAR_WATERFALL_ACTIVATION_CHANCE = 0.03
ALTAR_ENERGY_GAIN_WHEN_BURNING = 1.0
ALTAR_ENERGY_GAIN_WHEN_NOT_BURNING = 0.5
ALTAR_WATERFALL_ENERGY_INCREASE = 0.2

CAMPFIRE_FIRE_ENERGY_COST = 0.1
CAMPFIRE_ALTAR_ENERGY_COST = 0.1
CAMPFIRE_FOOD_COST = 4
CAMPFIRE_WOOD_COST = 2
CAMPFIRE_BURN_TIME_HOURS = 12

FOOD_GATHER_INTERVAL_HOURS = 3
GATHER_FOOD_FIRE_ENERGY_COST = 0.15
GATHER_FOOD_AMOUNT = 5

WOOD_GATHER_INTERVAL_HOURS = 6
GATHER_WOOD_FIRE_ENERGY_COST = 0.2
GATHER_WOOD_AMOUNT = 3

WATERFALL_ACTIVATION_ALTAR_ENERGY_COST = 0.25
WATERFALL_ENERGY_INCREASE_ON_ACTIVATION = 0.2
WATERFALL_BOOST_WATERFALL_ENERGY_COST = 0.35
WATERFALL_BOOST_AMOUNT = 0.85
WATERFALL_BOOST_INTERVAL_HOURS = 24

ENHANCE_FIRE_COST = 0.15
ENHANCE_ALTAR_COST = 0.15
ENHANCE_WATERFALL_COST = 0.15
ENHANCE_COST_INCREASE_EVERY_10 = 1.015  # +1,5%
ENHANCE_BASE_INCREASE = 0.0001
ENHANCE_TENTH_INCREASE = 0.001

