# Generated by Django 5.1.5 on 2025-01-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstate',
            name='last_food_gathering',
        ),
        migrations.RemoveField(
            model_name='playerstate',
            name='last_waterfall_boost',
        ),
        migrations.RemoveField(
            model_name='playerstate',
            name='last_wood_gathering',
        ),
        migrations.AddField(
            model_name='playerstate',
            name='last_fire_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstate',
            name='last_waterfall_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstate',
            name='last_altar_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstate',
            name='last_campfire_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
